# Let's Chat: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: docker-compose up

app:
  image: kaushik94/askmeanything:test_run_12
  links:
    - mongo
  ports:
    - 8080:8080
    - 5222:5222

mongo:
  image: mongo:latest
